# ------------------------------------------------------------------------------
# OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
# ------------------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
# Editor.....: Stefan Oehrli
# Date.......: 2018.12.10
# Revision...: --
# Purpose....: Simple compose file to create a 12.2 database
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0
# ------------------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# ------------------------------------------------------------------------------

services:
  tenc19:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: tenc19
    hostname: tenc19
    networks:
      default:
        aliases: 
          - tenc19.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/tenc19:/u01
      - ./config/tenc19:/u01/config
      - ./config/tenc19/etc:/u01/shared
      - ./config/common:/u01/common
    ports:
      - 4721:1521
      - 4723:1523
    environment:
      CONTAINER: 'FALSE'
      INSTANCE_INIT: /u01/config
      ORACLE_DBNAME: TENC19
      ORACLE_DB_UNIQUE_NAME: TENC19
      ORACLE_SID: TENC19     
      
  tencs1:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: tencs1
    hostname: tencs1
    networks:
      default:
        aliases: 
          - tencs1.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/tencs1:/u01
      - ./config/tenc/tencs1:/u01/config
      - ./config/tenc/shared:/u01/shared
      - ./config/common:/u01/common
    ports:
      - 4521:1521
      - 4523:1523
    environment:
      CONTAINER: 'FALSE'
      INSTANCE_INIT: /u01/config
      ORACLE_DBNAME: TENC
      ORACLE_DB_UNIQUE_NAME: TENCS1
      ORACLE_SID: TENCS1     

  tencs2:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: tencs2
    hostname: tencs2
    networks:
      default:
        aliases: 
          - tencs2.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/tencs2:/u01
      - ./config/tenc/tencs2:/u01/config
      - ./config/tenc/shared:/u01/shared
      - ./config/common:/u01/common
    ports:
      - 5521:1521
      - 5523:1523
    environment:
      CONTAINER: 'FALSE'
      INSTANCE_INIT: /u01/config
      ORACLE_DBNAME: TENC
      ORACLE_DB_UNIQUE_NAME: TENCS2
      ORACLE_SID: TENCS2  
      NO_DATABASE: TRUE   
  
  tencs3:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: tencs3
    hostname: tencs3
    networks:
      default:
        aliases: 
          - tencs3.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/tencs3:/u01
      - ./config/tenc/tencs3:/u01/config
      - ./config/tenc/shared:/u01/shared
      - ./config/common:/u01/common
    ports:
      - 6521:1521
      - 6523:1523
    environment:
      CONTAINER: 'FALSE'
      INSTANCE_INIT: /u01/config
      ORACLE_DBNAME: TENC
      ORACLE_DB_UNIQUE_NAME: TENCS3
      ORACLE_SID: TENCS3
      NO_DATABASE: TRUE    

  cdbencs1:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: cdbencs1
    hostname: cdbencs1
    networks:
      default:
        aliases: 
          - cdbencs1.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/cdbencs1:/u01
      - ./config/cdbenc/cdbencs1:/u01/config
      - ./config/cdbenc/shared:/u01/shared
      - ./config/common:/u01/common
    ports:
      - 4621:1521
      - 4623:1523
    environment:
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_DBNAME: CDBENC
      ORACLE_DB_UNIQUE_NAME: CDBENCS1
      ORACLE_SID: CDBENCS1     

  cdbencs2:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: cdbencs2
    hostname: cdbencs2
    networks:
      default:
        aliases: 
          - cdbencs2.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/cdbencs2:/u01
      - ./config/cdbenc/cdbencs2:/u01/config
      - ./config/cdbenc/shared:/u01/shared
      - ./config/common:/u01/common
    ports:
      - 5621:1521
      - 5623:1523
    environment:
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_DBNAME: CDBENC
      ORACLE_DB_UNIQUE_NAME: CDBENCS2
      ORACLE_SID: CDBENCS2  
      NO_DATABASE: TRUE   
  
  cdbencs3:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: cdbencs3
    hostname: cdbencs3
    networks:
      default:
        aliases: 
          - cdbencs3.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/cdbencs3:/u01
      - ./config/cdbenc/cdbencs3:/u01/config
      - ./config/cdbenc/shared:/u01/shared
      - ./config/common:/u01/common
    ports:
      - 6621:1521
      - 6623:1523
    environment:
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_DBNAME: CDBENC
      ORACLE_DB_UNIQUE_NAME: CDBENCS3
      ORACLE_SID: CDBENCS3
      NO_DATABASE: TRUE    

  cdbenc19:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.26.0.0
    container_name: cdbenc19
    hostname: cdbenc19
    networks:
      default:
        aliases: 
          - cdbenc19.trivadislabs.com
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/data/cdbenc19:/u01
      - ./config/cdbenc19:/u01/config
      - ./config/common:/u01/common
    ports:
      - 5521:1521
    environment:
      CONTAINER: 'TRUE'
      INSTANCE_INIT: /u01/config
      ORACLE_SID: CDBENC19
# - EOF -----------------------------------------------------------------
